# Generated by Django 3.2.7 on 2021-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon_percentage_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_item',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
